title: Default Page

tabs:
  content:
    columns:
      main:
        width: 2/3
        sections:
          fields:
            type: fields
            fields:
              # Opening ----------------------------
              openingTitle:
                type: text
                label: Opening title
                placeholder: "{{ page.title }}"
              openingSubtitle:
                type: textarea
                label: Opening subtitle
              openingImage:
                type: files
                max: 1
                label: Opening background Image
              # Opening ----------------------------

              blocks:
                type: blocks
                fieldsets:
                  - text
                  - image
                  - subpages

      sidebar:
        width: 1/3
        sections:
          pages:
            type: pages

          files:
            type: files

  seo: seo/page
