title: Project

tabs:
  content:
    columns:
      main:
        width: 2/3
        sections:
          fields:
            type: fields
            fields:
              coverImg:
                label: Cover image
                type: files
                min: 1
                max: 1
              tags:
                label: Tags
                type: tags
                options:
                  type: query
                  query: page.getAllTags
                width: 1/2
              year:
                label: Year
                type: number
                min: 1900
                max: 2100
                width: 1/2
              blocks:
                type: blocks
                fieldsets:
                  - text
                  - image
                  # - gallery
                  # - video
                  # - code
      sidebar:
        width: 1/3
        sections:
          pages: false
          files:
            type: files

  seo: seo/page
